version: '3.8'

services:
  idp.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: idp.db
    environment:
      SA_PASSWORD: '123456aA@'
      ACCEPT_EULA: 'Y'
    volumes:
      - idp_sqlserver_data:/var/opt/mssql
    restart: always
    ports:
      - '1436:1433'

  idp.api:
    image: ${DOCKER_REGISTRY-}idp.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: IDP/Dockerfile
    container_name: idp.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:IdentitySqlConnection=Server=idp.db;Database=IdentityServer;User Id=sa;Password=123456aA@;Multipleactiveresultsets=true;TrustServerCertificate=True;"
      - "IdentityServer:BaseUrl=http://localhost:6001"
      - "IdentityServer:IssuerUri=http://idp.api"
    depends_on:
      - idp.db
    ports:
      - '6001:80'
    restart: always

networks:
  default:
   external:
    name: idc_network

volumes:
  idp_sqlserver_data:
    external: false
