version: '3.8'

services:
  idp:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: idp_db
    environment:
      SA_PASSWORD: 'Passw0rd!'
      ACCEPT_EULA: 'Y'
    volumes:
      - idp_sqlserver_data:/var/opt/mssql
    restart: always
    ports:
      - '1436:1433'

volumes:
  idp_sqlserver_data:
    external: false
